test

diff --git a/.github/workflows/teste_git_actions.yml b/.github/workflows/teste_git_actions.yml
--- a/.github/workflows/teste_git_actions.yml
+++ b/.github/workflows/teste_git_actions.yml
@@ -16,25 +16,18 @@ jobs:
     runs-on: macOS-latest
 
     steps:
-    - uses: actions/checkout@main
-    - name: CodeCover
-      run: sh ./Scripts/ci-ios-code-coverage.sh
+    # - uses: actions/checkout@main
+    # - name: CodeCover
+    #   run: sh ./Scripts/ci-ios-code-coverage.sh
 
-    # - name: Run tests
-    #   uses: sersoft-gmbh/xcodebuild-action@v1
-    #   with:
-    #     project: doryQuiz/doryQuiz.xcodeproj
-    #     scheme: doryQuizTests
-    #     derived-data-path: ./output
-    #     destination: "OS=14.4,name=iPhone 12 Pro"
-    #     action: test
-    #     enable-code-coverage: true
-    # - name: install llvm
-    #   run: brew install llvm
+    - uses: actions/checkout@v2
+    - name: Test
+      run: |
+        xcodebuild -scheme doryQuizTests -resultBundlePath TestResults test
 
-    # - name: Test Coverage
-    #   uses: maxep/xcodebuild-lcov-action@0.1.0
-    #   with:
-    #     derived-data-path: ./CodeCoverage.xcresult
-    #     target: doryQuiz.app
-    #     output-file: ./coverage/lcov.info
+    - uses: kishikawakatsumi/xcresulttool@v1
+      with:
+        path: TestResults.xcresult
+        if: success() || failure()
+        # ^ This is important because the action will be run
+        # even if the test fails in the previous step.
