test

diff --git a/.github/workflows/teste_git_actions.yml b/.github/workflows/teste_git_actions.yml
--- a/.github/workflows/teste_git_actions.yml
+++ b/.github/workflows/teste_git_actions.yml
@@ -15,21 +15,14 @@ jobs:
     steps:
     - uses: actions/checkout@main
     - name: CodeCover
-      run: sh ./Scripts/ci-ios-code-coverage.sh
+      run: sh ./Scripts/quality-coverage.sh
 
-    # - uses: actions/checkout@v2
-    # - name: Test
-    #   run: |
-    #     xcodebuild -scheme doryQuizTests -resultBundlePath TestResults test
-
-    - uses: kishikawakatsumi/xcresulttool@v1
-      with:
-        path: CodeCoverage.xcresult
-        token: ${{ secrets.GITHUB_TOKEN }}
-        title: Xcode test results
-        show-passed-tests: true
-        show-code-coverage: true
-        upload-bundles: always
-      if: success() || failure()
-        # ^ This is important because the action will be run
-        # even if the test fails in the previous step.
+    # - uses: kishikawakatsumi/xcresulttool@v1
+    #   with:
+    #     path: CodeCoverage.xcresult
+    #     token: ${{ secrets.GITHUB_TOKEN }}
+    #     title: Xcode test results
+    #     show-passed-tests: false
+    #     show-code-coverage: true
+    # # - run: sh ./Scripts/quality-coverage.sh
+    #   if: success() || failure()
